temp: main.c
	gcc -Wall -g  -c /home/pi/Desktop/temperature/tempandhumidity/main.c -o obj/Debug/main.o
	gcc  -o bin/Debug/tempandhumidity obj/Debug/main.o -lm  /usr/lib/libwiringPi.so /usr/lib/libwiringPiDev.so
	./bin/Debug/tempandhumidity